#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    IR_collector_right, sensorAnalog)
#pragma config(Sensor, in2,    IR_collector_left, sensorAnalog)
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, dgtl2,  rangefinder,    sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  LED_Green,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  LED_Red,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, RedLED,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           motor_left,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motor_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          motor_crane,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// LED light control values.
const   int OFF = 0;
const   int ON  = 1;

void init_light_status(){
	// Turn of the red LED
	SensorValue(LED_Green)= OFF;
	SensorValue(LED_Red)= OFF;
}

task main(){
	// Initialize lighting status.
	init_light_status();
  while (true){
  	//if the button is pressed
  	if(SensorValue(button) == true){
  		SensorValue(LED_Red) = ON;
  		int min = 0;
  		while(min < 1){
  			//to break cycle if a certain IR threshold is met
  			if(SensorValue[IR_collector_left] < 1080){
  				min = 1;
  			}//if reaches
  			//turn the robot and scan
  			motor[motor_left] = 31;
				motor[motor_right] = 31;
				wait1Msec(100);

				//if it turns and sees a wall within 15cm then it should stop
				if(SensorValue[rangefinder] <= 15){
						motor[motor_left] = 0;
						motor[motor_right] = 0;
						wait1Msec(100000);
				}//end of wall see stop

				if(getMotorEncoder(port2) > 5000){//if it has completed an entire loop and no lower value has been found
					while(SensorValue[rangefinder] < 150){
						motor[motor_left] = 45;
						motor[motor_right] = 45;
					}//if while turn

					while(SensorValue[rangefinder] > 100){
						motor[motor_left] = 45;
						motor[motor_right] = -45;
					}//if while move forward
					//reset motor encoders incase the error case happens multiple times
					resetMotorEncoder(motor_left);
					resetMotorEncoder(motor_right);
				}//if statement for if the threshold has been met
  		}//while turning to find thingy
  		//stop for a second
  		SensorValue(LED_Red)= OFF;
			motor[motor_left] = 0;
			motor[motor_right] = 0;
			wait1Msec(100);
			//reset the motor endoders to make sure that the error cases would work
			resetMotorEncoder(motor_left);
			resetMotorEncoder(motor_right);

			//approaches the target using the range finder (ultrasonic) until it is roughly 50cm away
			while(SensorValue[rangefinder] > 50){
				motor[motor_left] = 31;
    		motor[motor_right] = -31;
			}//end of while look to approach target

			motor[motor_left] = 0;
			motor[motor_right] = 0;
			wait1Msec(100);
			//turn back a little bit to check again to make sure that it doesn't start the motors again and move away from the actual target
			motor[motor_left] = -45;
			motor[motor_right] = -45;
			wait1Msec(700);
			//reset the motor endoders to make sure that the error cases would work
			resetMotorEncoder(motor_left);
			resetMotorEncoder(motor_right);

			SensorValue(LED_Red) = ON;
			//second check at a lower threshold to make sure it approaches the target with greater precision
			min = 0;
  		while(min < 1){

  			//to break cycle if a certain IR threshold is met
  			if(SensorValue[IR_collector_left] < 1000){
  				min = 1;
  			}//if reaches

  			//turn the robot and scan
  			motor[motor_left] = 31;
				motor[motor_right] = 31;
				wait1Msec(100);

				//if it turns and sees a wall withing 15cm then it should stop
				if(SensorValue[rangefinder] <= 15){
						motor[motor_left] = 0;
						motor[motor_right] = 0;
						wait1Msec(100000);
				}//end of if statment of wall sensing

				if(getMotorEncoder(port2) > 5000){//if it has completed an entire loop and no lower value has been found stop motors
					motor[motor_left] = 0;
					motor[motor_right] = 0;
					wait1Msec(100000);
				}//if statement

  		}//while turning to find thingy

  		//approach the target until the robot is 20cm away
  		while(SensorValue[rangefinder] > 20){
				motor[motor_left] = 31;
    		motor[motor_right] = -31;
			}//end of while look to approach target

			SensorValue(LED_Red) = OFF;
			SensorValue(LED_Green) = ON;

			// once the robot is at the appropiate distance in the relation to the target, it stops so that it can initialte the ball drop
			motor[motor_right] = 0;
 	  	motor[motor_left] = 0;
	 	  //drop ball
	 	  motor[motor_crane] = 40;
	 	 	wait1Msec(200);
	 	  motor[motor_crane]= 0;
	 	  wait1Msec(600);
	 	  wait1Msec(1000);

	 	  //code to move away from the target once the task is complete
	 	  while(SensorValue[rangefinder] < 70){
	 	  	motor[motor_left] = -31;
	 	  	motor[motor_right] = 31;
	 	  	SensorValue(LED_Green) = OFF;
	 	  }//end of while loop move back

	 	  //after robot moves backt the re-raise the arm
	 	  motor[motor_left] = 0;
	 	  motor[motor_right] = 0;
	 	  motor[motor_crane] = -40;
	 	 	wait1Msec(200);
	 	  motor[motor_crane]= 0;
	  }//if button is presssed
	}//while(true)
} //end of task main
